openapi: 3.0.0
info:
  title: SmartAPI OHLC Service
  version: 1.0.0
servers:
  - url: https://smartapi-ohlc-gpt.vercel.app
paths:
  /api/get-ohlc:
    get:
      summary: Get OHLC data for a stock
      description: Fetches historical OHLC candles from your SmartAPI Vercel backend.
      operationId: getOhlcData
      parameters:
        - name: stock_symbol
          in: query
          required: true
          description: Stock symbol (e.g. INFY, HDFCBANK, RELIANCE)
          schema:
            type: string
        - name: exchange
          in: query
          required: false
          description: Exchange (default NSE)
          schema:
            type: string
            default: NSE
        - name: days
          in: query
          required: false
          description: Number of daily candles to fetch
          schema:
            type: integer
            default: 30
      responses:
        "200":
          description: Successful OHLC response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  symbol:
                    type: string
                    example: INFY
                  data:
                    type: array
                    description: Array of OHLCV rows
                    items:
                      type: array
                      description: [timestamp, open, high, low, close, volume]
                      items:
                        oneOf:
                          - type: string   # timestamp
                          - type: number   # OHLCV values

